### ISSUE TITLE
Inject license after shebang

### ISSUE THREAD

**Issue by kriskowal** [uber/uber-licence#2]
`#!` is a valid first line of a Node.js script. License must fall under it for Unix to recognize the magic number.

**Comment by Raynos** [comment]
Looks like we detect it ( https://github.com/uber/uber-licence/blob/master/valid-licences.js#L27 )

It's just that the adding logic ( https://github.com/uber/uber-licence/blob/master/bin/licence#L128 ) doesn't deal with it.
