### ISSUE TITLE
Why is this so important?

### ISSUE THREAD

**Issue by abdulhannanali** [uber/uber-licence#30]
Hello,

Why is it  important for Uber to put the MIT License in each file again and again. Doesn't it get redundant and is just unnecessary bloat with each file that contains code? Does it serve benefit over the inclusion of **LICENSE** file that contains the license? 

I was just exploring Uber's OSS stuff and happened to come on this repo. I know this question might seem unnecessary but I am just curious, I'd welcome any point of views on this topic. Thanks :+1:

**Comment by Raynos** [comment]
For legal purposes we have a licence header on every source file.

I am not a lawyer but I believe our lawyers want every file to have a licence. Having a licence in a git repository that applies to all files is not sufficient.

There are other large companies that do similar things:

 - https://github.com/facebook/fbzmq/blob/master/fbzmq/async/AsyncSignalHandler.cpp#L1-L10
 - https://github.com/apple/swift/blob/master/lib/Driver/Compilation.cpp#L1-L13

I personally do not like the MIT licence header for every file, but it's a legal compromise to be able to do open source development at a large company.

**Comment by abdulhannanali** [comment]
Thanks for your response @Raynos Yes I see, Facebook does have this thing too. It's always better to be careful. Appreciate it! Closing the issue!
